use crate::models::Customer;
use std::cell::RefCell;
use std::rc::Rc;

/// Creates a percentage discount closure that captures the discount percentage by value.
///
/// Demonstrates returning a closure (`impl Fn`) using the `move` keyword.
pub fn make_percentage_discount(percentage: u32) -> impl Fn(u32) -> u32 {
    move |amount_cents| (amount_cents * percentage) / 100
}

/// Creates a threshold discount closure (e.g., "$10 off orders over $100").
///
/// If `amount_cents` is greater than or equal to `min_cents`, returns `discount_cents`; otherwise 0.
pub fn make_threshold_discount(min_cents: u32, discount_cents: u32) -> impl Fn(u32) -> u32 {
    move |amount_cents| {
        if amount_cents >= min_cents {
            discount_cents
        } else {
            0
        }
    }
}

/// Creates a VIP customer discount closure that captures the VIP discount rate.
pub fn make_vip_discount(vip_rate: u32) -> impl Fn(&Customer, u32) -> u32 {
    move |customer, amount_cents| {
        if customer.is_vip || customer.has_tag("vip") {
            (amount_cents * vip_rate) / 100
        } else {
            0
        }
    }
}

/// Evaluates a list of discount closures and returns the total combined discount.
///
/// Demonstrates passing closures as generic parameters bounded by `Fn`.
pub fn calculate_total_promotions<F>(amount_cents: u32, rules: &[F]) -> u32
where
    F: Fn(u32) -> u32,
{
    rules.iter().map(|rule| rule(amount_cents)).sum()
}

/// Evaluates a list of discount closures and returns the single largest discount.
pub fn find_best_promotion<F>(amount_cents: u32, rules: &[F]) -> u32
where
    F: Fn(u32) -> u32,
{
    rules
        .iter()
        .map(|rule| rule(amount_cents))
        .max()
        .unwrap_or(0)
}

/// An audit tracker that records discount applications using a mutating closure (`FnMut`).
///
/// Demonstrates `FnMut` capturing and mutating enclosing environment state across invocations.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DiscountAuditor {
    pub total_discount_given: u32,
    pub operations_count: u32,
}

impl DiscountAuditor {
    pub fn new() -> Self {
        Self {
            total_discount_given: 0,
            operations_count: 0,
        }
    }

    /// Records an applied discount, mutating internal accounting counters.
    pub fn record(&mut self, discount_cents: u32) {
        self.total_discount_given += discount_cents;
        self.operations_count += 1;
    }
}

impl Default for DiscountAuditor {
    fn default() -> Self {
        Self::new()
    }
}

/// A trait object closure stored on the heap, allowing heterogeneous closures to be stored in a collection.
pub type BoxedDiscount = Box<dyn Fn(u32) -> u32>;

/// A dynamic promotion engine holding heterogeneous discount closures in a heap-allocated `Vec<Box<dyn Fn(u32) -> u32>>`.
///
/// In Chapter 18, we discovered that every closure has a unique anonymous compiler type,
/// making it impossible to store different closures (e.g. percentage + threshold) in a standard `Vec<F>`.
/// `Box<dyn Fn(u32) -> u32>` solves this by allocating the closures on the heap and using dynamic dispatch!
pub struct PromotionPipeline {
    rules: Vec<BoxedDiscount>,
}

impl PromotionPipeline {
    pub fn new() -> Self {
        Self { rules: Vec::new() }
    }

    /// Adds a closure rule to the pipeline, boxing it onto the heap as a trait object.
    pub fn add_rule<F>(&mut self, rule: F)
    where
        F: Fn(u32) -> u32 + 'static,
    {
        self.rules.push(Box::new(rule));
    }

    /// Adds an already-boxed closure rule.
    pub fn add_boxed_rule(&mut self, rule: BoxedDiscount) {
        self.rules.push(rule);
    }

    /// Calculates the sum of all discounts generated by all rules in the pipeline.
    pub fn apply_all(&self, amount_cents: u32) -> u32 {
        self.rules.iter().map(|rule| rule(amount_cents)).sum()
    }

    /// Evaluates all rules and returns the single largest discount amount.
    pub fn apply_best(&self, amount_cents: u32) -> u32 {
        self.rules
            .iter()
            .map(|rule| rule(amount_cents))
            .max()
            .unwrap_or(0)
    }

    pub fn len(&self) -> usize {
        self.rules.len()
    }

    pub fn is_empty(&self) -> bool {
        self.rules.is_empty()
    }
}

impl Default for PromotionPipeline {
    fn default() -> Self {
        Self::new()
    }
}

/// A shared audit tracker demonstrating `Rc<RefCell<T>>` for single-threaded interior mutability.
///
/// Multiple parts of the store (or different pipeline evaluations) can hold cloned `Rc` handles
/// to the same `SharedAuditor`. Calls to `record` use `borrow_mut()` to mutate the inner
/// `DiscountAuditor` even when calling through an immutable reference `&self`!
#[derive(Debug, Clone, Default)]
pub struct SharedAuditor {
    inner: Rc<RefCell<DiscountAuditor>>,
}

impl SharedAuditor {
    pub fn new() -> Self {
        Self {
            inner: Rc::new(RefCell::new(DiscountAuditor::new())),
        }
    }

    /// Records a discount application through an immutable reference `&self`,
    /// demonstrating runtime-checked interior mutability.
    pub fn record(&self, discount_cents: u32) {
        self.inner.borrow_mut().record(discount_cents);
    }

    pub fn total_discount_given(&self) -> u32 {
        self.inner.borrow().total_discount_given
    }

    pub fn operations_count(&self) -> u32 {
        self.inner.borrow().operations_count
    }

    /// Returns the active reference count of owners sharing this auditor.
    pub fn strong_count(&self) -> usize {
        Rc::strong_count(&self.inner)
    }
}
